### ISSUE TITLE
Sales Order Creation

### ISSUE THREAD

**Issue by lfsolutions** [DeBortoliWines/openerp-java-api#11]
Hello Team,

We are trying to create a Sales Order with the API like one below but unable to do that.

Is it possible to help us to do that ?

````
 openERPSession.startSession();
	   
ObjectAdapter salesAd = openERPSession.getObjectAdapter("sale.order");
ObjectAdapter salesOLAd = openERPSession.getObjectAdapter("sale.order.line");


Row newSL1 = salesOLAd.getNewRow(new String[]{"product_id","product_uom_qty"});
newSL1.put("product_id", 51);
newSL1.put("product_uom_qty", 2);
salesOLAd.createObject(newSL1);
System.out.println("Order Line 1 is : "+newSL1.getID());

Row newSO = salesAd.getNewRow(new String[]{"partner_id"});
newSO.put("partner_id", 1);
salesAd.createObject(newSO);
System.out.println("SO is : "+newSO.getID());


newSO.putMany2ManyValue("order_line", new Object[]{newSL1.getID()}, true);
salesAd.writeObject(newSO, true);

System.out.println("Our Sales Order is "+ newSO.getID());

````

The error is 
java.lang.String cannot be cast to java.lang.Integer

**Comment by flotho** [comment]
Hy,

First, the relation between orders and orders line is not a many2many.
Personnaly I would have done it in 2 parts :
First create the order THEN create order lines and pass the order_id as a value in the order line.
This way has always worked for me.

regards

**Comment by lfsolutions** [comment]
Is it possible to write a code for me ?

Or just the linking Sales Order with Order Line ?

Thanks for your reply again

**Comment by xsalefter** [comment]
> Is it possible to write a code for me ?

Hey @flotho , he asking your [request for quotation](http://en.wikipedia.org/wiki/Request_for_quotation) . :wink:

**Comment by flotho** [comment]
@xsalefter, thanks my english is not so accurate!

**Comment by flotho** [comment]
Hy @lfsolutions sorry if I didn't undertsnad that you were asking for a commercial proposal.
Did you achieved your job? Do you still need help?
regards

**Comment by flotho** [comment]
Hy @lfsolutions , 

I close the issue
