### ISSUE TITLE
Use of exec_workflow on leads

### ISSUE THREAD

**Issue by bwilmus** [DeBortoliWines/openerp-java-api#12]
Hi,

I would like to use the exec_workflow method to transform a lead into an opportunity.
What is the signal that I must use in that specific case?

Regards,

Bernard

**Comment by flotho** [comment]
Hy @bwilmus 

As you can probably see here : http://59919-8-0-e75e2c.runbot.odoo.com/web?db=59919-8-0-e75e2c-all&debug=#id=12&view_type=form&model=crm.lead&action=576 there is no workflow for turning lead to opportunity. So you won't be able to use workflow.
Additionnaly, opportunity and leads are the same object but in different states.
You'll have to use a simple execute method. Maybe on this one : https://github.com/odoo/odoo/blob/8.0/addons/crm/crm_lead.py#L715

Regards

**Comment by flotho** [comment]
@bwilmus 

You could have some information on the class definition : https://sourceforge.net/p/openerpjavaapi/wiki/Class%20Overview/
And some piece of code here https://sourceforge.net/p/openerpjavaapi/discussion/general/thread/1315d8a9/ (even if the purpose was not the same, the first tries to executecommand gave some success)

**Comment by flotho** [comment]
@bwilmus, also have a look there : http://sourceforge.net/p/openerpjavaapi/discussion/general/thread/a7a4aba8/?limit=25#7fe0 at the end of the thread

**Comment by flotho** [comment]
Hy @bwilmus , did you solved your issue?

regards

**Comment by bwilmus** [comment]
No, I did create opportunities instead of leads.

**Comment by flotho** [comment]
Hi @bwilmus ,
There is no workflow (as odoo workflow) attached on crm.leads.
The evolution and change of states is done by code and through the call of specific function.
Maybe you could find which one and call this one with the executeCommand method of the java API
