### ISSUE TITLE
Validate invoice

### ISSUE THREAD

**Issue by Lawra** [DeBortoliWines/openerp-java-api#22]
Hello,

It is possible to validate an invoice? I can create one with the following code:

ObjectAdapter invoiceObj = openERPSession.getObjectAdapter("account.invoice")
Row newBillOpenERP = invoiceObj.getNewRow(["account_id", 'partner_id', 'company_id', 'sent', 'state', 'amount_tax', 'payment_term', 'date_invoice', 'payment_type', 'date_due'] as String[])

newBillOpenERP.put("partner_id", idPartner) //required
newBillOpenERP.put("company_id", 1) //required
newBillOpenERP.put("account_id", 519) //required
newBillOpenERP.put("sent", bill.sent)
newBillOpenERP.put("state", 'draft')
newBillOpenERP.put("payment_term", PaymentTerm.get(bill.paymentTermId).openERPId)
newBillOpenERP.put("payment_type", PaymentType.get(bill.paymentTypeId).openERPId) 

invoiceObj.createObject(newBillOpenERP)
log.info("New OpenERP bill ID: " + newBillOpenERP.getID())

Now I want to validate the invoice, I tried with callFunction() but I don't exactly how to use it.

**Comment by flotho** [comment]
Hi,

Don't use the callFunction, there is a workflow method :
https://github.com/DeBortoliWines/openerp-java-api/issues/4
https://github.com/DeBortoliWines/openerp-java-api/issues/10

regards

**Comment by Lawra** [comment]
I'm trying to validate the invoice with this code:
invoiceObj.executeWorkflow(newBillOpenERP, "validate")

but I get this error:
com.debortoliwines.openerp.api.OpeneERPApiException: Could not find signal with name 'validate' for object 'account.invoice'

How can I find the possible signals to use in account.invoice?

**Comment by flotho** [comment]
Validate don't seems to be the correct signal, did you print your workflow, everything is visible in it. Then you'll be able to choose which signal to use
