### ISSUE TITLE
recommendations for use: relational objects

### ISSUE THREAD

**Issue by beltrewilton** [DeBortoliWines/openerp-java-api#35]
Hello team, this work like a charm!

** this isn't a issue**

i have the next use case: get pricelist of assigned user in point of sales
  -> user login -> "retrieve user odoo id" -> get pos.config: id -> get product.pricelist: id -> get pricelist object

after session start: 

             session.startSession();
             int userID = session.getUserID(); // I added this public method

           // search for pos_config:id
            ObjectAdapter objectAdapter = session.getObjectAdapter(RES_USERS);
            FilterCollection filter = new FilterCollection();
            filter.add("id", "=", userID);
            RowCollection rows = objectAdapter.searchAndReadObject(filter, SQLBuilder.RES_USERS_FIELDS);
            rows.forEach(row -> {
                posConfig.setId((Integer) ((Object[]) row.get(ru.POS_CONFIG))[0]);
                posConfig.setName((String) ((Object[]) row.get(ru.POS_CONFIG))[1]);
            });

            // search for pricelist:id
            objectAdapter = session.getObjectAdapter(POS_CONFIG);
            filter = new FilterCollection();
            filter.add("id", "=", posConfig.getId());
            rows = objectAdapter.searchAndReadObject(filter, SQLBuilder.POS_CONFIG_FIELDS);
            rows.forEach(row -> {
                pricelistItem.setId((Integer) ((Object[]) row.get(pc.PRICELIST_ID))[0]);
                pricelistItem.setName((String) ((Object[]) row.get(pc.PRICELIST_ID))[1]);
            });

            // search for pricelist object
            objectAdapter = session.getObjectAdapter(PRICELIST_ITEM);
            filter = new FilterCollection();
            filter.add("id", "=", pricelistItem.getId());
            rows = objectAdapter.searchAndReadObject(filter, SQLBuilder.PRICELIST_FIELDS);
            rows.forEach(row -> {
                pricelistItem.setId(row.getID());
                pricelistItem.setName((String) row.get(pl.NAME));
                pricelistItem.setBase((Integer) row.get(pl.BASE));
                pricelistItem.setDisplay_name((String) row.get(pl.DISPLAY_NAME));
                ..........

I made 4 calls to get the price list,
There is a mechanism more optimal, less call?

Thanks Team!

**Comment by flotho** [comment]
Hi @beltrewilton , 
I think it's hard to do better as there is no way from xmlrpc to get much more than the object that is reached. So you'll have to do 4 calls.
BTW, it's exactly the way the internal API (ORM) works. The relational fields are returned thanks to a call to the DB.
So :
* internal API = 4 calls
* XMLRPC : 4 calls either
If you succeed to do better than the internal API, let us know ;-)
