### ISSUE TITLE
writeObject does not send the context

### ISSUE THREAD

**Issue by jeffallen** [DeBortoliWines/openerp-java-api#36]
Using code like this:

    public static void main(String[] args) {
        Session openERPSession = new Session("localhost", 8069, "HQ1", "admin", "admin");
        try {
            // startSession logs into the server and keeps the userid of the logged in user
            openERPSession.startSession();
            ObjectAdapter products = openERPSession.getObjectAdapter("product.product");

            // Setup things used for searching
            FilterCollection filters = new FilterCollection();
            filters.add("default_code","=","DINFDEXT1N5");
            String[] fields = new String[]{"name"};

            System.out.println("With no context (inherits language of the user):");
            RowCollection rc = products.searchAndReadObject(filters, fields);
            if (rc.size() != 1) {
                throw new Exception("Expected only one product.");
            }
            System.out.println("context lang:" + openERPSession.getContext().getLanguage());
            System.out.println("Name:" + rc.get(0).get("name"));

            System.out.println("");
            System.out.println("Set context to English:");
            openERPSession.getContext().setLanguage("en_MF");
            rc = products.searchAndReadObject(filters, fields);
            if (rc.size() != 1) {
                throw new Exception("Expected only one product.");
            }
            System.out.println("context lang: " + openERPSession.getContext().getLanguage());
            System.out.println("Name:" + rc.get(0).get("name"));

            System.out.println("");
            System.out.println("Set context to French:");
            openERPSession.getContext().setLanguage("fr_MF");
            rc = products.searchAndReadObject(filters, fields);
            if (rc.size() != 1) {
                throw new Exception("Expected only one product.");
            }
            System.out.println("context lang: " + openERPSession.getContext().getLanguage());
            System.out.println("Name:" + rc.get(0).get("name"));

            Row theRow = rc.get(0);
            theRow.put("name", theRow.get("name") + "*");
            boolean success = products.writeObject(theRow, true);

            if (success)
                System.out.println("Update was successful");

        } catch (Exception e) {
            System.out.println("Error while reading data from server:\n\n" + e.getMessage());
        }
    }

I find that the second time it is run, the French product name ends up in product.product:name instead of in the ir.translations table, as it should. (en_MF and fr_MF are custom languages in my installation. You could see the same thing by loading en-US and fr-FR, then using the "Translate" UI to translate a product name to fr-FR)

The following fix to include context with writes fixes the problem:

```
  diff --git a/src/com/debortoliwines/openerp/api/OpenERPCommand.java   b/src/com/debortoliwines/openerp/api/OpenERPCommand.java
  index 901172b..a8d4111 100644
  --- a/src/com/debortoliwines/openerp/api/OpenERPCommand.java
  +++ b/src/com/debortoliwines/openerp/api/OpenERPCommand.java
  @@ -100,7 +100,7 @@ public class OpenERPCommand {
           */
          public boolean writeObject(String objectName, int id, HashMap<String, Object> valueList) throws XmlRpcException{
                  boolean result = false;
  -               result = (Boolean) session.executeCommand(objectName, "write", new Object[] {id, valueList});
  +               result = (Boolean) session.executeCommand(objectName, "write", new Object[] {id, valueList, session.getContext()});
                  return result;
          }
```

I am using the 7.0 branch, but it looks like the same bug exists in the master branch as well.

**Comment by flotho** [comment]
Hi @jeffallen ,

Your proposal looks good but IMO it's not the proper way to deal with context.
As you know in v8/v9/v10 and in the new API, the context i sno more in the signature of the method.
So it could be a better way to implement a method that change the context in the session class.
I'll try this later

**Comment by jeffallen** [comment]
I'm working on a fork from openerp 6, so I don't know about anything other than that.

**Comment by flotho** [comment]
Hi @jeffallen ,
Ok for the 6 release.
Maybe you could also try to work with the context class : https://github.com/DeBortoliWines/openerp-java-api/blob/master/src/main/java/com/debortoliwines/odoo/api/Context.java#L39
In this part you could put parameters to the context. Maybe you already had this part in your fork.
Regards

**Comment by jeffallen** [comment]
Using openERPSession.getContext().setLanguage("fr_MF"); works fine, the language is in the context object on the client side. For reading, it is sent and OpenERP uses it to look in the right place in the database, and the expected data comes back, according to the context. For writing, the context is not sent, and so the write goes to the wrong place.

**Comment by flotho** [comment]
great so this issue could be closed.

Thanks
