### ISSUE TITLE
groupby in searchAndReadObject()

### ISSUE THREAD

**Issue by cfadam** [DeBortoliWines/openerp-java-api#5]
OpenERP 7 supports groupby. It would be great to have the groupby option in searchAndReadObject(). 

Thanks,

Adam

**Comment by flotho** [comment]
@cfadam I don't think it's possible.
First the OpenERP search method has no paramater for group by even in v8 see there : https://www.odoo.com/documentation/8.0/reference/orm.html#openerp.models.Model.search
Group by is really a client option.
Yet you could sort your search and the with java make some filters or loop on your datas

**Comment by flotho** [comment]
Hi,

I confirmed that it's a client function, so it could not be implemented in the API. You'll have to recode the behaviour on the resultset you get
