### ISSUE TITLE
Odoo 8, openerp 1.3.0 char error

### ISSUE THREAD

**Issue by viandanteoscuro** [DeBortoliWines/openerp-java-api#55]
Hi,

I'm using PDI 8.1 and openerp java api 1.3, but i got this error from server response:

Failed to parse server's response: An invalid XML character (Unicode: 0xc) was found in the element content of the document.
at org.pentaho.di.trans.steps.openerp.objectoutput.OpenERPObjectOutput.processRow(OpenERPObjectOutput.java:96)

Have you any suggestions?

The content of the xml that i send to the server is ok.

Thanks
Massimo

**Comment by flotho** [comment]
hi @viandanteoscuro ,
I assume that you're not using the right version of the API.
Have a look to the readme, the versions are explained. for v8, you should use the 2.x API.

regards

**Comment by viandanteoscuro** [comment]
I've installed the plugin via marketplace.
And the plugin comes with 1.3 version.
Can I change safetly the jar?

**Comment by flotho** [comment]
yes of course
pull the repo and run the maven build target to have the appropriate version,
