### ISSUE TITLE
Add support for boolean results when calling callObjectFunction on the Command class

### ISSUE THREAD

**Issue by pietercvdm** [DeBortoliWines/openerp-java-api#7]
See https://sourceforge.net/p/openerpjavaapi/discussion/general/thread/a7a4aba8/#7fe0

The callObjectFunction expects a Object[] to be returned.  Should revisit that and maybe let people do their own type casting.

**Comment by flotho** [comment]
Hi @pietercvdm 

Great proposal, I thing that we should add methods that would evaluate the type of return. This improvements will be really powerfull combined with the API v2.
