### ISSUE TITLE
Wrong handling of error responses

### ISSUE THREAD

**Issue by BorLaze** [DeBortoliWines/openerp-java-api#9]
I try to create new product:

```
Row newProduct = productObjectAdapter.getNewRow(fields());
newProduct.put("name", "product-1171");
newProduct.put("categ_id", "1171");
newProduct.put("type", "product");
newProduct.put("procure_method", "make_to_stock");
newProduct.put("supply_method", "buy");
productObjectAdapter.createObject(newProduct);
```

All works fine. 

But when I comment out setup of required field "supply_method", in OpenERP server logs got error messages like

```
2014-12-11 16:17:29,301 922 ERROR : bad query: 
IntegrityError: null value in column "supply_method" violates not-null constraint
DETAIL:  Failing row contains (.....).

2014-12-11 16:17:29,306 922 ERROR : Integrity Error
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set
.....
```

It's OK, because "supply_method" is missed.

But in Java-client I got exception like

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at org.apache.xmlrpc.parser.XmlRpcResponseParser.addResult(XmlRpcResponseParser.java:61)
    .....
```

As far as I found, it is because OpenErp returns faultCode as string while XMLRPC expects integer value.

I want to have server's response instead of ClassCastException.
Is any way to fix it? Can I inject custom ResponseParser, for example?

**Comment by veloutin** [comment]
It seems like this lib is connecting to the legacy xmlrpc interface, at /xmlrpc/. OpenERP has supported integer fault codes for a few years now. Depending on the version, you can find the non-legacy version at /openerp/xmlrpc/ (v7) /openerp/xmlrpc/1/ (v7) /xmlrpc/2/ (v8). I haven't looked at the v6.

**Comment by bwrsandman** [comment]
Namely, in https://github.com/DeBortoliWines/openerp-java-api/blob/7dbbf6a1f7aacf3e93035a9fe9c5783f5092e9e8/src/com/debortoliwines/openerp/api/OpenERPXmlRpcProxy.java#L55-L57

The faultcodes should be ints if they are replaced with:
```
	private final String RPC_COMMON_URL = "/openerp/xmlrpc/1/common";
	private final String RPC_OBJECT_URL = "/openerp/xmlrpc/1/object";
	private final String RPC_DATABASE_URL = "/openerp/xmlrpc/1/db";
```

In 7.0, using `"/xmlrpc/*"` will go through the function [`wsgi_xmlrpc_legacy`](https://github.com/odoo/odoo/blob/0a1f52ccb5b3704d65760e392f123fab15e3847f/openerp/service/wsgi_server.py#L218), and exceptions will be made with [`xmlrpc_handle_exception_legacy`](https://github.com/odoo/odoo/blob/0a1f52ccb5b3704d65760e392f123fab15e3847f/openerp/service/wsgi_server.py#L125). These return strings as faultcodes.

Using `/openerp/xmlrpc/1/*` will go through the function [`wsgi_xmlrpc_1`](https://github.com/odoo/odoo/blob/0a1f52ccb5b3704d65760e392f123fab15e3847f/openerp/service/wsgi_server.py#L150), and exceptions will be made with [`xmlrpc_handle_exception_1`](https://github.com/odoo/odoo/blob/0a1f52ccb5b3704d65760e392f123fab15e3847f/openerp/service/wsgi_server.py#L92). These should return ints.

**Comment by flotho** [comment]
Won't it be possible to identify or specify dynamically which API could be used?
regards

**Comment by bwrsandman** [comment]
You can get it with `RPC_DATABASE_URL`.

In python:
```python
>>> from xmlrpc import client
>>> client.ServerProxy("%s/openerp/xmlrpc/1/db" % host).server_version()
"7.0"
```

**Comment by veloutin** [comment]
Another option would be to try the recent API and catch a 404, maybe.

**Comment by flotho** [comment]
Hi @BorLaze ,

Could you try with latest master branch?

regards

**Comment by pirardn** [comment]
Hello,

we updated the XML-RPC library to be able to manage int and String faultCode.

Take a look at [https://github.com/nowina-solutions/xmlrpc](url)

Hope this help

**Comment by stephanesalah** [comment]
hi,
i have the same pb with exception returning.

Can you tell me please if this issue was finally solved and if the update of xmlrpc has solved the pb can you please send me an updated link ?

Thanks for all

Stéphane
